Controllers/VocabularyController.cs
using KhoaLuanTotNghiep.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Speech;
using System.Speech.Synthesis;
namespace KhoaLuanTotNghiep.Controllers
{
    public class VocabularyController : Controller
    {
        // GET: Vocabulary
        private Model1 model;
        public VocabularyController()
        {
            model = new Model1();
           
        }
        public ActionResult Index(string id)
        {

            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountInfo = null;
            List<CHUDE> listcd = new List<CHUDE>();
            List<CHUDE> listChude = new List<CHUDE>();
            if (id == null)
            {
                listcd = model.CHUDEs.Where(t=>t.IDTK1 == null || t.IDTK1 == account.IDTK).ToList();
            }
            else
            {
                listcd = model.CHUDEs.Where(t => t.IDTK1 == null || t.IDTK1 == account.IDTK).Where(t => t.TENCD.ToLower().Contains(id.ToLower())).ToList();
            }
            for(int i = 0; i < listcd.Count; i++)
            {
                if(listcd[i].TENCD.ToLower().Equals("yêu thích"))
                {
                    listChude.Add(listcd[i]);  
                }
            }
            for (int i = 0; i < listcd.Count; i++)
            {
                if (!listcd[i].TENCD.ToLower().Equals("yêu thích"))
                {
                    listChude.Add(listcd[i]);
                }
            }
            //List<TUVUNGONTAP> tUVUNGONTAPs = model.TUVUNGONTAPs.Join(model.CHUDEs, tv => tv.IDCD, cd => cd.IDCD, (tv, cd) => new { tv, cd }).Where(t => t.cd.IDTK == account.IDTK).Select(t => t.tv).ToList();
            List<TUVUNGONTAP> listTv = new List<TUVUNGONTAP>();
            foreach(var item in listChude)
            {
                var tvcd = model.TUVUNGONTAPs.Where(t => t.IDCD == item.IDCD).ToList();
                foreach(var item1 in tvcd)
                {
                    listTv.Add(item1);
                }
            }
            if (account != null)
            {
                accountInfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            }
            Tuple<List<CHUDE>, List<TUVUNGONTAP>> tuple = new Tuple<List<CHUDE>, List<TUVUNGONTAP>>(listChude, listTv);
            ViewData["tuple"] = tuple;
            return View(accountInfo);

        }

        public ActionResult Topic(string topic)
        {
            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            model.CHUDEs.Add(new CHUDE(topic, account.IDTK,null,null));
            model.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult deleteTopic(int id)
        {
            CHUDE chude = model.CHUDEs.Where(t => t.IDCD == id).SingleOrDefault();
            List<TUVUNGONTAP> listTV = model.TUVUNGONTAPs.Where(t => t.IDCD == id).ToList();
            if(listTV.Count > 0)
            {
                foreach(var item in listTV)
                {
                    model.TUVUNGONTAPs.Remove(item);
                    model.SaveChanges();
                }
            }
            model.CHUDEs.Remove(chude);
            model.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult details(int id,string searchWord)
        {
            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountInfo = null;
            if (account != null)
            {
                accountInfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            }
          
            List<TUVUNGONTAP> listTV = new List<TUVUNGONTAP>();
            if(searchWord == null)
            {
                listTV = model.TUVUNGONTAPs.Where(t => t.IDCD == id).ToList();
            }
            else
            {
                listTV = model.TUVUNGONTAPs.Where(t => t.IDCD == id).Where(t=>t.TENTV.ToLower().Contains(searchWord.ToLower())).ToList();
            }
            
            ViewData["IDCD"] = id;
            ViewData["ListTV"] = listTV;
            return View(accountInfo);
        }
        public PartialViewResult Flashcard(int data1)
        {
            TUVUNGONTAP tuvung = model.TUVUNGONTAPs.Where(t => t.IDTV == data1).SingleOrDefault();
            return PartialView(tuvung);
        }
       

        [HttpPost]
        public ActionResult EditVocab(HttpPostedFileBase file,string id,string name, string meaning, string example,string idCD)
        {
            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountinfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            int ID = Int32.Parse(id);
            int IDCD = Int32.Parse(idCD);
            TUVUNGONTAP tuvung = model.TUVUNGONTAPs.Where(t => t.IDTV == ID).SingleOrDefault();
            tuvung.TENTV = name;
            tuvung.NGHIATV = meaning;
            tuvung.VDTV = example;
            if (file != null)
            {
                string filename = Path.GetFileName(file.FileName);
        string extension = Path.GetExtension(file.FileName);
        string path = Path.Combine(Server.MapPath("/Img/"), filename);
        tuvung.ANHTUVUNG = "/Img/" + filename;
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (file.ContentLength <= 1000000)
                    {
                        if (model.SaveChanges() > 0)
                        {
                            file.SaveAs(path);
                        }
                    }
                }
            }
            else
            {
                model.SaveChanges();
            }
            return RedirectToAction("details", new { id = IDCD });
        }
        public ActionResult DeleteTV(int id,int idCD)
        {
            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountinfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            TUVUNGONTAP tuvung = model.TUVUNGONTAPs.Where(t => t.IDTV == id).SingleOrDefault();
            CHUDE chude = model.CHUDEs.Where(t => t.IDCD == idCD).SingleOrDefault();
            model.TUVUNGONTAPs.Remove(tuvung);
            model.SaveChanges();
            return RedirectToAction("details",new {id = idCD });
        }
        public PartialViewResult FlashcardCreate(int data1)
        {
            CHUDE chude = model.CHUDEs.Where(t => t.IDCD == data1).SingleOrDefault();
            return PartialView(chude);
        }

        public ActionResult CreateTV(HttpPostedFileBase file, string name, string meaning, string example, int idCD)
        {
            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountinfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            //int IDCD = Int32.Parse(idCD);

            if (file != null)
            {
                string filename = Path.GetFileName(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("/Img/"), filename);
                model.TUVUNGONTAPs.Add(new TUVUNGONTAP(name, meaning, null,example,"/Img/" + filename, idCD));
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (file.ContentLength <= 1000000)
                    {
                        
                        if (model.SaveChanges() > 0)
                        {
                            file.SaveAs(path);
                        }
                    }
                }
            }
            else
            {
                model.TUVUNGONTAPs.Add(new TUVUNGONTAP(name, meaning, null, example ,null, idCD));
                model.SaveChanges();
            }
            List<TUVUNGONTAP> listTV = model.TUVUNGONTAPs.Where(t => t.IDCD == idCD).ToList();
            return RedirectToAction("details", new { id = idCD });
        }

        public ActionResult SearchTopic(string searchTopic)
        {
            return RedirectToAction("Index", new { id = searchTopic });
        }

        public ActionResult SearchWord(string searchWord,int idcd)
        {

            return RedirectToAction("details", new { searchWord = searchWord, id = idcd });
        }

        public ActionResult TopicEdit(string topic , string topicID)
        {
            int TopicID = Int32.Parse(topicID);
            CHUDE chude = model.CHUDEs.Where(t => t.IDCD == TopicID).SingleOrDefault();
            chude.TENCD = topic;
            model.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Practice(int id)
        {
            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountinfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            ViewData["id"] = id;
            return View(accountinfo);
        }

        public ActionResult match(int id)
        {
            var rnd = new Random();

            TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
            THONGTINTAIKHOAN accountinfo = model.THONGTINTAIKHOANs.Where(t => t.IDTK == account.IDTK).SingleOrDefault();
            List<TUVUNGONTAP> listTV = model.TUVUNGONTAPs.Where(t => t.CHUDE.IDCD == id).ToList();
            List<TUVUNGONTAP> listTV1 = new List<TUVUNGONTAP>();
            if (listTV.Count > 5)

Views/Shared/_Header.cshtml
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="~/Content/style.css" media="screen" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <meta name="keywords" content="Make learning fun!, FLASHCARD, EXAM">
        <meta name="description" content="">
        <meta name="page_type" content="np-template-header-footer-from-plugin">
        <title>Home</title>
        <link rel="stylesheet" href="~/Content/homepage/Home.css" media="screen">
        <link rel="stylesheet" href="~/Content/homepage/nicepage.css" media="screen">

        <script class="u-script" type="text/javascript" src="~/Content/jquery.js" defer=""></script>
        <script class="u-script" type="text/javascript" src="~/Content/nicepage.js" defer=""></script>
        <meta name="generator" content="Nicepage 3.12.1, nicepage.com">
        <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
        <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700,700i,900,900i">





        <meta property="og:title" content="Home">
        <meta property="og:type" content="website">
        <meta name="theme-color" content="#478ac9">
        <link rel="canonical" href="index.html">
        <meta property="og:url" content="index.html">*@
    <style>
        navbar1{
            z-index:5px;
        }
    </style>
</head>
@model KhoaLuanTotNghiep.Models.THONGTINTAIKHOAN
@using KhoaLuanTotNghiep.Models;

    <div class="navbar1">
        <h3>
            @Html.ActionLink("Learning English Fun", "Home", "Home")
        </h3>
        @if (Model == null)
        {
            <ul>
                <li><a data-toggle="modal" data-target="#SignInModal" style="cursor:pointer;">Đăng nhập</a></li>
                <li><a data-toggle="modal" data-target="#SignUpModal" style="cursor:pointer;">Đăng ký</a></li>
            </ul>
        }
        else
        {
    <ul>
        @{
            string[] tachten = null;
            string ten = null;
            if (Model.TEN.Length > 8)
            {
                tachten = Model.TEN.Split(' ');
                ten = tachten[tachten.Length - 1];
                <li>@Html.ActionLink(ten, "AccountInfo", "Account", new { id = Model.IDTK }, null)</li>
            }
            else
            {
                <li>@Html.ActionLink(Model.TEN, "AccountInfo", "Account", new { id = Model.IDTK }, null)</li>
            }
        }

        <li>@Html.ActionLink("Đăng xuất", "Logout", "Home")</li>
    </ul>
        }

    </div>


@*<header class="u-clearfix u-header u-white u-header" id="sec-2270">
        <div class="u-clearfix u-sheet u-sheet-1">
            <nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1">
                <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
                    <a class="u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
                        <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <defs>
                                <symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;">
                                    <rect y="1" width="16" height="2"></rect>
                                    <rect y="7" width="16" height="2"></rect>
                                    <rect y="13" width="16" height="2"></rect>
                                </symbol>
                            </defs>
                        </svg>
                    </a>
                </div>
                <div class="u-nav-container">
                    <ul class="u-nav u-unstyled u-nav-1">
                        <li class="u-nav-item">

                            @Html.ActionLink("Home", "Home", "Home", null, new { @class = "u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base", @style = "padding: 10px 20px;" })
                        </li>
                        @if (Model == null)
                        {
                            <li class="u-nav-item">
                                <a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#Login" data-toggle="modal" data-target="#SignInModal" style="padding: 10px 20px;">Sign in</a>
                            </li>
                            <li class="u-nav-item">
                                <a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#Register" data-toggle="modal" data-target="#SignUpModal" style="padding: 10px 20px;">Sign up</a>
                            </li>
                        }
                        else
                        {
                            <li class="u-nav-item">
                                @Html.ActionLink(Model.TEN, "AccountInfo", "Account", new { id = Model.IDTK }, new { @class = "u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" ,@style = "padding: 10px 20px;" })
                            </li>
                            <li class="u-nav-item">
                                @Html.ActionLink("Logout", "Logout", "Home",null,new { @class = "u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base", @style = "padding: 10px 20px;" })
                            </li>
                        }

                    </ul>
                </div>
                <div class="u-nav-container-collapse">
                    <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                        <div class="u-sidenav-overflow">
                            <div class="u-menu-close"></div>
                            <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                                <li class="u-nav-item">
                                    @Html.ActionLink("Home", "Home", "Home", null, new { @class = "u-button-style u-nav-link" })
                                </li>
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" href="#Login" data-toggle="modal" data-target="#SignInModal">Sign in</a>
                                </li>
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" href="#Register" data-toggle="modal" data-target="#SignUpModal">Sign up</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
                </div>
            </nav>

            @Html.ActionLink("Learning English Fun", "Home", "Home", null, new { @class = "u-text u-text-default u-text-1", @style = "color:gray;" })
        </div>
    </header>*@





<div class="modal" id="SignInModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Đăng nhập</h4>

            </div>

            @using (Html.BeginForm("SignIn", "Home"))
            {
                <!-- Modal body -->
                <div class="modal-body">
                    <input type="text" name="username" class="w-100 namesignin" placeholder="Tên đăng nhập ..." required><br>

                    <input type="password" name="password" class="mt-2 w-100 passsignin" placeholder="Mật khẩu ..." required><br>

                    <input type="submit" value="Đăng nhập" class=" mt-3 btn btn-primary w-100">
                </div>
            }
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-success w-50 create-btn" data-dismiss="modal">Tạo tài khoản mới</button>

            </div>

        </div>
    </div>
</div>
<div class="modal" id="SignUpModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Đăng ký tài khoản</h4>
            </div>

            @using (Html.BeginForm("SignUp", "Home"))
            {
                <!-- Modal body -->
                <div class="modal-body">
                    <input type="text" name="name" class="mt-2 w-100 mb-2" placeholder="Họ và tên ..." required><br>
                    <input type="text" name="username" class="w-100" placeholder="Tên đăng nhập ..." required><br>
                    <input type="text" name="password" class="mt-2 w-100" placeholder="Mật khẩu ..." required><br>
                    <label class="mt-2">Ngày sinh:</label>
                    <div class="birthday">
                        <select name="day" id="day" style="width:32.5%;" required>
                            <option value="0">Ngày</option>
                            @for (int i = 1; i < 32; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                        <select name="month" id="month" style="width:32.5%;" required>
                            <option value="0">Tháng</option>
                            @for (int i = 1; i < 13; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                        <select name="year" id="year" style="width:32.5%;" required>
                            <option value="0">Năm</option>
                            @for (int i = DateTime.Now.Year - 100; i <= DateTime.Now.Year; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                    <label class="mt-2">Giới tính:</label>
                    <div class="Gender">
                        <div class="male">
                            <label for="male">Nam</label>
                            <input type="radio" id="male" name="gender" value="1" checked>
                        </div>
                        <div class="female">
                            <label for="female">Nữ</label>
                            <input type="radio" id="female" name="gender" value="2">
                        </div>
                    </div>
                    <input type="submit" value="Đăng ký" class=" mt-3 btn btn-success w-100">

                </div>
            }

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(`.create-btn`).click(function (event) {
            event.preventDefault();
            jQuery.noConflict();
            $(`#SignUpModal`).modal('show');
        });
        $(`input`).attr("autocomplete", "off");
    });
</script>

Views/Shared/_Layout.cshtml
@model KhoaLuanTotNghiep.Models.THONGTINTAIKHOAN
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css" media="screen" />
   
</head>
<body>
    @RenderPage("~/Views/Shared/_Header.cshtml", new { Model })
    <br />
    <div class="bodyLayout" style="margin-top:18px;">
        @RenderPage("~/Views/Shared/_VerticalBar.cshtml", new { Model })
        <div class="renderbody">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css" media="screen" />

</head>
<body>
    @RenderPage("~/Views/Shared/_HeaderAdmin.cshtml", new { Model })
    <br />
    <div class="bodyLayout" style="margin-top:18px;">
        @RenderPage("~/Views/Shared/_VerticalBarAdmin.cshtml")
        <div class="renderbody">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_VerticalBar.cshtml
@using KhoaLuanTotNghiep.Models;
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/style.css" media="screen" />
@{
    Model1 model = new Model1();
    TAIKHOAN account = model.TAIKHOANs.Where(t => t.USING == true).SingleOrDefault();
}
<style>
    .navbar2 {
        z-index: 1;
        background-image:url('../../Img/vertical background.jpg');
        background-size:100% 100%;
        background-color:rgba(255,255,255,0.2);
        background-blend-mode:lighten;
    }
    .account, .vocabulary, .Group, .Exam {
        width: 100%;
        height:100px;
        display:flex;
        justify-content:center;
        padding:35px 0;
        background-image:url(../../Img/thumuc.png);
        background-size:100% 100%;
    }
    
</style>
<div class="navbar2" style="width:15%;border:none;box-shadow:0 0 7px gray;position:fixed;top:43px;padding:0;">
    <div class="account">
        @Html.ActionLink("Tài khoản", "AccountInfo", "Account", new { id = account.IDTK }, new { @class = "btn", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>
    <div class="vocabulary">
        @Html.ActionLink("Từ vựng", "Index", "Vocabulary", null ,new { @class = "btn", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>

    <div class="Exam">
        @Html.ActionLink("Bài tập", "Index", "Exam", null,new { @class = "btn", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>
    <div class="Group">
        @Html.ActionLink("Học nhóm", "Group", "Account",null, new { @class = "btn", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>


</div>

Views/Shared/_VerticalBarAdmin.cshtml
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/style.css" media="screen" />
@using KhoaLuanTotNghiep.Models;
@{ 
    Model1 model = new Model1();
    ADMIN admin = model.ADMINs.Where(t => t.USING == true).SingleOrDefault();
}
<style>
    .navbar2 {
        z-index: 1;
        background-image: url('../../Img/vertical background.jpg');
        background-size: 100% 100%;
        background-color: rgba(255,255,255,0.2);
        background-blend-mode: lighten;
    }
    .account, .vocabulary, .listAccount, .practice {
        width: 100%;
        height: 100px;
        display: flex;
        justify-content: center;
        padding: 35px 0;
        background-image: url(../../Img/thumuc.png);
        background-size: 100% 100%;
    }
</style>
<div class="navbar2" style="width:15%;border:none;box-shadow:0 0 7px gray;position:fixed;top:42px;">
    <div class="account">
        @Html.ActionLink("Tài khoản", "AdminInfo", "Home", new { id = admin.IDTK }, new { @class = "btn ", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>
    <div class="vocabulary">
        @Html.ActionLink("Quản lý từ vựng", "TopicAdmin", "Home", new { @class = "btn ", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>

    <div class="practice">
        @Html.ActionLink("Quản lý luyện tập", "Practice", "Home", new { @class = "btn ", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>

    <div class="listAccount" style="display:flex;flex-direction:row;">

        @Html.ActionLink("Quản lý tài khoản", "Admin", "Home", new { @class = "btn ", @style = "border:none;color:white;font-size:1.25rem;font-weight:600;border-radius:0;border-radius:0.5rem;height:65px;width:212px;" })
    </div>





</div>